# Site settings
title: "Horoman â€“ Interaction Design"
description: "Personal homepage of Roman Horokhovatskyy an Interaction Designer based in Milan, Italy."
keywords: "Roman, Horokhovatskyy, @horoman, @h0r0m4n, Interaction Design, User Interface Design, User Experience Design"
author: "Roman Horokhovatskyy"
role: "Senior Interaction Designer"
location: "Milan, Italy"
company: "Spindox"
company-url: "https://spindox.it"
nickname: "h0r0m4n"
mail: "roman.horokhovatskyy@gmail.com"
starting: "2008"

# Jekyll settings
# source: ./src
sass:
  sass_dir: css
  style: compressed